src/laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

#### ACCOUNT ####
Route::group(['middleware' => ['role:customer'], 'prefix' => 'account', 'namespace' => 'App\Http\Controllers\Account'], function () {
    Route::get('', 'AccountController@index')->name('account.index');
    Route::get('{user}/edit', 'AccountController@edit')->name('account.edit');
    Route::put('{user}', 'AccountController@update')->name('account.update');
    Route::delete('{user}', 'AccountController@destroy')->name('account.destroy');

    //News
    Route::group(['prefix' => 'news'], function () {
        Route::get('', 'NewsController@index')->name('account.news.index');
    });
});
#### /ACCOUNT ####

#### ADMIN ####
Route::group(['middleware' => ['role:admin'], 'prefix' => 'admin', 'namespace' => 'App\Http\Controllers\Admin'], function () {
    Route::get('', 'AdminController@index')->name('admin.index');

    Route::resource('news', 'NewsController');
});
#### /ADMIN ####

src/laravel/app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * New Model
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $image
 */
class News extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'title',
        'description',
        'image',
    ];
}

src/laravel/app/Http/Controllers/Account/NewsController.php
<?php

namespace App\Http\Controllers\Account;

use App\Http\Controllers\Controller;
use App\Models\News;
use App\Services\NewsService;

class NewsController extends Controller
{
    /**
     * @var NewsService
     */
    protected NewsService $service;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(NewsService $service)
    {
        $this->service = $service;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('News.index', ['news' => $this->service->filter()]);
    }
}

src/laravel/app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\NewsFormRequest;
use App\Http\Resources\NewsResource;
use App\Models\News;
use App\Services\DTO\NewsDTO;
use App\Services\NewsService;
use Illuminate\Http\Request;

class NewsController extends Controller
{
    /**
     * @var NewsService
     */
    protected NewsService $service;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(NewsService $service)
    {
        $this->service = $service;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('News.index', ['news' => $this->service->filter()]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('News.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(NewsFormRequest $request, NewsDTO $newsDTO)
    {
        $status = 'Record successfully created';

        try {
            $this->service->store($newsDTO->createFromArray($request->validated()));
        }catch (\Throwable $e){
            $status = $e->getMessage();
        }

        return redirect()->route('news.index')->with('status', $status);
    }

    /**
     * Display the specified resource.
     */
    public function show(News $news)
    {
        return view('News.show', ['news' => $news]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(News $news)
    {
        return view('News.edit', ['news' => $news]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(NewsFormRequest $request, NewsDTO $newsDTO, News $news)
    {
        $status = 'Record successfully updated';

        try {
            $this->service->update($news, $newsDTO->createFromArray($request->validated()));
        }catch (\Throwable $e){
            $status = $e->getMessage();
        }

        return redirect()->back()->with('status', $status);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(News $news)
    {
        $status = 'Record successfully deleted';

        try {
            $this->service->destroy($news);
        }catch (\Throwable $e){
            $status = $e->getMessage();
        }

        return redirect()->back()->with('status', $status);
    }
}

src/laravel/resources/views/News/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><a href="{{route('news.index')}}"><</a> {{ __('Add News') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{route('news.store')}}">
                        @csrf
                        <input type="hidden" id="new_image" name="new_image" value="true">
                        <div class="mb-3">
                            <label for="title" class="form-label">Title</label>
                            <input type="text" class="form-control" id="title" placeholder="News Title" name="title" value="{{ old('title') }}">
                        </div>
                        <div class="mb-3">
                            <label for="description" class="form-label">Description</label>
                            <textarea class="form-control" id="description" rows="3" name="description">{!! old('description') !!}</textarea>
                        </div>
                        <div class="mb-3">
                            <input type="submit" value="Add" class="btn btn-success">
                            <a href="{{route('news.index')}}" class="btn btn-info">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

src/laravel/resources/views/News/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><a href="{{route('news.index')}}"><</a> {{ __('Edit News') }} "{{$news->title}}"</div>

                <div class="card-body">
                    <form method="POST" action="{{route('news.update', ['news' => $news->id])}}">
                        @method('PUT')
                        @csrf
                        <div class="mb-3">
                            <label for="title" class="form-label">Title</label>
                            <input type="text" class="form-control" id="title" placeholder="News Title" name="title" value="{{ old('title') ?? $news->title }}">
                        </div>
                        <div class="mb-3">
                            <label for="description" class="form-label">Description</label>
                            <textarea class="form-control" id="description" rows="3" name="description">{!! old('description') ?? $news->description !!}</textarea>
                        </div>
                        <div class="mb-3">
                            <label for="new_image" class="form-label">Generate new photo</label>
                            <input type="checkbox" id="new_image" name="new_image"><br/>
                            <img src="{{$news->image}}" alt="{{$news->title}}" style="width: 200px">
                        </div>
                        <div class="mb-3">
                            <input type="submit" value="Save" class="btn btn-success">
                            <a href="{{route('news.index')}}" class="btn btn-info">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

src/laravel/resources/views/News/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{ __('News') }}
                    @if(auth()->user()->hasRole('admin'))
                        <a href="{{route('news.create')}}" title="Add News">+</a>
                    @endif
                </div>

                <div class="card-body">
                    @if($news->count() > 0)
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col" style="width: 30px">#</th>
                                    <th scope="col" style="width: 75px">Image</th>
                                    <th scope="col">Title</th>
                                    @if(auth()->user()->hasRole('admin'))
                                        <th scope="col" style="width: 225px">Actions</th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($news as $item)
                                    <tr>
                                        <td>{{$item->id}}</td>
                                        <td class="text-center"><img src="{{$item->image}}" alt="" style="width: 90%" /></td>
                                        <td>{{$item->title}}</td>

                                        @if(auth()->user()->hasRole('admin'))
                                            <td>
                                                <a href="{{route('news.show', ['news' => $item->id])}}" class="btn btn-success">Show</a>
                                                <a href="{{route('news.edit', ['news' => $item->id])}}" class="btn btn-info">Edit</a>
                                                <form method="POST" action="{{route('news.destroy', ['news' => $item->id])}}" style="display: inline">
                                                    @method('DELETE')
                                                    @csrf
                                                    <input type="submit" value="Delete" class="btn btn-danger">
                                                </form>
                                            </td>
                                        @endif
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    @else
                        <div class="alert alert-info" role="alert">
                            Records not found
                        </div>
                    @endif

                    <div class="d-flex justify-content-center">
                        {{$news->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

src/laravel/resources/views/News/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><a href="{{route('news.index')}}"><</a> "{{$news->title}}"</div>

                <div class="card-body">
                    <b>Title: </b>{{$news->title}}<br/>
                    <b>Description: </b><br/>{{$news->description}}<br/>
                    <img src="{{$news->image}}" alt="{{$news->title}}" style="width: 200px"><br/><br/><br/>

                    <a href="{{route('news.index')}}" class="btn btn-info">Go to List</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection